// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Grid_View_Task.Entities
{
    [Index(nameof(title1), Name = "titleind")]
    public partial class title
    {
        [Key]
        [StringLength(6)]
        public string title_id { get; set; }
        [Required]
        [Column("title")]
        [StringLength(80)]
        public string title1 { get; set; }
        [Required]
        [StringLength(12)]
        public string type { get; set; }
        [StringLength(4)]
        public string pub_id { get; set; }
        [Column(TypeName = "money")]
        public decimal? price { get; set; }
        [Column(TypeName = "money")]
        public decimal? advance { get; set; }
        public int? royalty { get; set; }
        public int? ytd_sales { get; set; }
        [StringLength(200)]
        public string notes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime pubdate { get; set; }

        [ForeignKey(nameof(pub_id))]
        [InverseProperty(nameof(publisher.titles))]
        public virtual publisher pub { get; set; }
    }
}